# Generated by Django 3.1.5 on 2021-01-21 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20210121_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='eps',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.eps'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.rol'),
        ),
    ]
