# Generated by Django 3.1.5 on 2021-01-21 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_auto_20210121_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='eps',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.eps'),
        ),
    ]
